### ISSUE TITLE
Tagging SignedDistanceFields

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGraphics/SignedDistanceFields.jl#2]
Hi,
I'd be great if you could register and tag `SignedDistanceFields` ;)
If you need any help, let me know!

Best,
Simon

**Comment by yurivish** [comment]
It looks like I could use some assistance. Pkg.publish failed and trying to manually create a pull request is giving odd errors. All I want to do is tag v0.0.1; the package is already registered.

**Comment by SimonDanisch** [comment]
Did you try deleting the github auth-token!?
`settings --> personal access token --> package manager token` .. Or so ;)
That's a known issue with publish.

**Comment by yurivish** [comment]
Yup – I looked into it when going through the FAQ but didn't see a token there in the first place.

**Comment by SimonDanisch** [comment]
Well you can always just go into your METADA folder, check if the changes from the tagging are there and then just push it to a fork of METADATA. That's sadly how I need to do it most of the time.

**Comment by yurivish** [comment]
right; I'd forgotten how that process works. 

Pull request made! https://github.com/JuliaLang/METADATA.jl/pull/3564

**Comment by SimonDanisch** [comment]
Great, thanks a lot :)
If you want others to help out more easily, you could also think about putting the package into JuliaGraphics. If that makes sense for you!

I think you should also add a REQUIRE file saying `julia 0.3`...
Sorry for not comming up with that earlier^^

**Comment by yurivish** [comment]
I'd actually be happy to transfer it over – this isn't something I'm currently keeping up with and it looks like it's become a useful part of the large Julia graphics effort, which is great!

**Comment by SimonDanisch** [comment]
Cool! Can you move it there? I can then do the rest if you like.

**Comment by yurivish** [comment]
Done!
